[package]
name = "model-categories"
version = "0.1"
lean_version = "leanprover-community/lean:3.50.3"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "83d4ea51c7000b7bae35771854e19554478de821"}
dold-kan = {git = "https://github.com/joelriou/dold-kan", rev = "a083fe264275774ac49ac520caf25f2ee29debb1"}
